setup.py
src/vivarium_ciff_sam/constants/models.py
src/vivarium_ciff_sam/model_specifications/model_spec.yaml

Tested in an interactive sim to see that initialization of the three causes is in line with the expected prevalence. Also tested to see that remission and incidence looks to be in line with the values expected from the incidence and remission/dwell-time data.

add diarrhea, measles, and lri cause models

---

src/vivarium_ciff_sam/constants/data_keys.py
src/vivarium_ciff_sam/constants/data_values.py
src/vivarium_ciff_sam/constants/results.py
src/vivarium_ciff_sam/data/loader.py
src/vivarium_ciff_sam/tools/make_artifacts.py

Tested by successfully building artifact using the branch of `vivarium_inputs` in this pr: https://github.com/ihmeuw/vivarium_inputs/pull/280 . 
Will update `vivarium_inputs` dependency in a later PR after this has been released.

add data for wasting model

---

src/vivarium_ciff_sam/constants/data_values.py
src/vivarium_ciff_sam/data/loader.py
src/vivarium_ciff_sam/model_specifications/ciff_sam.yaml

update lri prevalence to be compatible with incidence

---

src/vivarium_ciff_sam/components/wasting.py

This makes it a little easier to run the equations in a notebook

refactor wasting equations to make it easier to test

---

src/vivarium_ciff_sam/components/wasting.py

Please review carefully to make sure I haven't made any mistakes in transcribing these equations.

replace numbers in equations with duration constants

---

src/vivarium_ciff_sam/constants/data_keys.py
src/vivarium_ciff_sam/data/loader.py

For now using standard data for pem. This may change.

load pem data

---

src/vivarium_ciff_sam/components/wasting.py

Implemented PEM. Tested by checking that the disability weight and excess mortality is appropriately applied to the MAM and SAM states.

add pem disability weight and emr

---

src/vivarium_ciff_sam/data/loader.py

Successfully loaded the GBD 2020 wasting exposure with this.

load child wasting exposure data from GBD 2020

---

src/vivarium_ciff_sam/constants/metadata.py
src/vivarium_ciff_sam/data/loader.py
src/vivarium_ciff_sam/data/utilities.py

I was able to load wasting exposure from GBD 2020 before, but I was pulling with GBD 2019 age bins and estimation years, which are different in GBD 2020. Now I am able to successfully load the correct age bins and years of GBD 2020.

load GBD 2020 wasting exposure using GBD 2020 age bins

---

src/vivarium_ciff_sam/data/loader.py
src/vivarium_ciff_sam/data/utilities.py

Successfully loaded GBD 2020 wasting RRs.

load child wasting rr data from GBD 2020

---

src/vivarium_ciff_sam/data/loader.py

PAFs for child wasting are not available yet in GBD 2020, so we're calculating them from the RR and exposure values we have already loaded from GBD 2020. Previously we were loading from GBD 2019.

calculate and load GBD 2020 wasting pafs

---

src/vivarium_ciff_sam/components/observers.py
src/vivarium_ciff_sam/components/wasting.py
src/vivarium_ciff_sam/constants/data_keys.py
src/vivarium_ciff_sam/constants/data_values.py
src/vivarium_ciff_sam/constants/models.py
src/vivarium_ciff_sam/constants/results.py
src/vivarium_ciff_sam/data/loader.py
src/vivarium_ciff_sam/data/utilities.py

Implementation of the wasting model. 
Successfully ran simulation and tested initial transition rates in interactive simulation to see that they produced sensible values.
I would appreciate it if you can look carefully at the equations and compare them to the commented line above them defining what the equation should be.

implement wasting model transition equations

---

src/vivarium_ciff_sam/constants/data_keys.py
src/vivarium_ciff_sam/data/loader.py
src/vivarium_ciff_sam/data/utilities.py

Successfully loaded PEM data in the artifact

load pem data into artifact

---

src/vivarium_ciff_sam/components/wasting.py

birth prevalence is needed in the model, since otherwise exposure takes too long to catch up to expected levels.

add wasting birth prevalence to model

---

src/vivarium_ciff_sam/constants/data_keys.py
src/vivarium_ciff_sam/data/loader.py

Verifed that this correctly loads stunting data into the artifact

load child stunting data

---

src/vivarium_ciff_sam/constants/results.py
src/vivarium_ciff_sam/results_processing/process_results.py

Temporarily replace wasting stratification with stunting stratification

update results processing to handle stunting stratification

---

src/vivarium_ciff_sam/components/__init__.py
src/vivarium_ciff_sam/components/intervention.py
src/vivarium_ciff_sam/components/treatment.py
src/vivarium_ciff_sam/constants/data_keys.py
src/vivarium_ciff_sam/constants/data_values.py
src/vivarium_ciff_sam/constants/metadata.py
src/vivarium_ciff_sam/constants/scenarios.py
src/vivarium_ciff_sam/model_specifications/branches/scenarios.yaml
src/vivarium_ciff_sam/model_specifications/ciff_sam.yaml

This includes SQ-LNS coverage and the effect on both wasting and stunting

implement SQ-LNS treatment coverage and wasting effect

---

src/vivarium_ciff_sam/components/treatment.py
src/vivarium_ciff_sam/constants/data_values.py
src/vivarium_ciff_sam/utilities.py

Also updated SAM_K to be calculated using both quantile values as suggested by @NathanielBlairStahn

incorporate draw-level uncretainty into sq-lns effectiveness

---

src/vivarium_ciff_sam/components/intervention.py
src/vivarium_ciff_sam/model_specifications/branches/scenarios.yaml
src/vivarium_ciff_sam/model_specifications/ciff_sam.yaml

This branches file is intended to create 15 branches - 3 intervention scenarios x 5 x-factor relative risk values. @collijk can you confirm I'm using the branches file correctly to do this?

implement x-factor risk

---

src/vivarium_ciff_sam/components/observers.py
src/vivarium_ciff_sam/constants/data_keys.py
src/vivarium_ciff_sam/model_specifications/branches/scenarios.yaml
src/vivarium_ciff_sam/model_specifications/ciff_sam.yaml

We weren't capturing the alternative treatment category.

track alternative treatment in stratification

---

src/vivarium_ciff_sam/model_specifications/branches/scenarios.yaml
src/vivarium_ciff_sam/model_specifications/ciff_sam.yaml

Somehow in merge resolution I left the x-factor configs commented out.

uncomment x-factor configurations and branches

---

src/vivarium_ciff_sam/components/__init__.py
src/vivarium_ciff_sam/components/wasting.py
src/vivarium_ciff_sam/components/x_factor.py
src/vivarium_ciff_sam/model_specifications/ciff_sam.yaml

Use child wasting propensity as the x-factor propensity

update x-factor exposure

---

src/vivarium_ciff_sam/components/intervention.py
src/vivarium_ciff_sam/constants/data_keys.py
src/vivarium_ciff_sam/constants/data_values.py
src/vivarium_ciff_sam/constants/scenarios.py
src/vivarium_ciff_sam/model_specifications/ciff_sam.yaml

Implemented the scale-up of interventions as a linear increase rather than a step upon coverage initiation.
I would love to get feedback regarding whether there is utility in adding `LinearScaleUpIntervention` to `vivarium_public_health`, since we scale interventions up linearly in this fashion quite often.

implement linear intervention scale-up

---

src/vivarium_ciff_sam/components/intervention.py
src/vivarium_ciff_sam/components/lbwsg.py
src/vivarium_ciff_sam/components/treatment.py
src/vivarium_ciff_sam/components/wasting.py
src/vivarium_ciff_sam/components/x_factor.py

counterpart to these update to vph https://github.com/ihmeuw/vivarium_public_health/pull/246

make methods private

---

src/vivarium_ciff_sam/components/lbwsg.py

- *Category*: bugfix
- *JIRA issue*: [MIC-2595](https://jira.ihme.washington.edu/browse/MIC-2595)
- *Research reference*: [LBWSG RR modeling strategy](https://vivarium-research.readthedocs.io/en/latest/gbd2019_models/risk_effects/low_birthweight_short_gestation/index.html#vivarium-modeling-strategy)
Uses standard paf getter function.
Fixes som dimensional issues in calculating relative risks
Rebuilt the artifact and verified that the data looks as expected.

fix bugs in lbwsg risk effect component

---

src/vivarium_ciff_sam/components/lbwsg.py
src/vivarium_ciff_sam/components/observers.py
src/vivarium_ciff_sam/components/risk.py
src/vivarium_ciff_sam/components/wasting.py
src/vivarium_ciff_sam/constants/data_keys.py
src/vivarium_ciff_sam/constants/data_values.py
src/vivarium_ciff_sam/constants/results.py
src/vivarium_ciff_sam/data/loader.py
src/vivarium_ciff_sam/model_specifications/ciff_sam.yaml
src/vivarium_ciff_sam/results_processing/process_results.py

- *Category*: post-processing/refactor
- *JIRA issue*: [MIC-2602](https://jira.ihme.washington.edu/browse/MIC-2602)
Added post processing for maternal supplementation stratification. Also refactored post-processing code to make it more readable.
Ran `make_results` on a single run

implement post-processing for birth stratifications

---

src/vivarium_ciff_sam/results_processing/process_results.py

- *Category*: bugfix
- *JIRA issue*: N/A
Need to cast from int to str
Ran results processing on completed run

fix bug in transition counts results processing

---

src/vivarium_ciff_sam/model_specifications/ciff_sam.yaml

- *Category*: model change
- *JIRA issue*: [MIC-2856](https://jira.ihme.washington.edu/browse/MIC-2856)
- *Research reference*: [Child wasting effect on diarrheal diseases](https://vivarium-research.readthedocs.io/en/latest/gbd2019_models/risk_effects/wasting/index.html#diarrheal-diseases)
Change effect from diarrhea incidence rate to emr
Verified pipeline values look correct

modifies wasting to affect diarrhea emr

---

src/vivarium_ciff_sam/components/wasting.py
src/vivarium_ciff_sam/constants/data_values.py
src/vivarium_ciff_sam/constants/metadata.py
src/vivarium_ciff_sam/data/loader.py
src/vivarium_ciff_sam/data/utilities.py
src/vivarium_ciff_sam/model_specifications/ciff_sam.yaml

- *Category*: model change
- *JIRA issue*: [MIC-2857](https://jira.ihme.washington.edu/browse/MIC-2857)
- *Research reference*: [Diarrhea transitions](https://vivarium-research.readthedocs.io/en/latest/gbd2019_models/causes/diarrheal_diseases/index.html#id15)
Update diarrheal diseases remission rate
Added metadata constant for Artifact draw columns
Made artifact and verified that remission rate has changed.

update diarrhea remission rate

---

src/vivarium_ciff_sam/data/loader.py

- *Category*: bugfix
- *JIRA issue*: [MIC-2516](https://jira.ihme.washington.edu/browse/MIC-2516)
Update affected measure in wasting relative risk artifact
Ran make artifacts and verified index looked as expected.

fix diarrhea measure affectd by wasting

---

src/vivarium_ciff_sam/model_specifications/branches/scenarios.yaml
src/vivarium_ciff_sam/model_specifications/ciff_sam.yaml

- *Category*: model change
- *JIRA issue*: [MIC-2878](https://jira.ihme.washington.edu/browse/MIC-2878)
- *Research reference*: 
Research team decided they prefer the alternative sam k value
N/A

remove baseline sam k scenario

---

src/vivarium_ciff_sam/components/__init__.py
src/vivarium_ciff_sam/components/wasting.py
src/vivarium_ciff_sam/constants/data_values.py
src/vivarium_ciff_sam/model_specifications/ciff_sam.yaml

- *Category*: implementation
- *JIRA issue*: [MIC-2833](https://jira.ihme.washington.edu/browse/MIC-2833)
- *Research reference*: [Vicious cycle equations](https://vivarium-research.readthedocs.io/en/latest/gbd2019_models/risk_effects/diarrheal_diseases/index.html#application-of-risk-effects)
Implemented the vicious cycle equations
Fixed bug in observers where stratification by columns didn't work properly
Refactored `RiskEffect` to simplify `_get_target_modifier` function and enable subclassing for the `DiarrheaRiskEffect`
Mild refactoring of wasting equations functions' data loaders.
Verified that simulation works as expected in an Interactive sim.

implement vicious cycle

---

src/vivarium_ciff_sam/components/observers.py
src/vivarium_ciff_sam/model_specifications/ciff_sam.yaml

- *Category*: observers
- *JIRA issue*: [MIC-2680](https://jira.ihme.washington.edu/browse/MIC-2680)
Stratify wasting and stunting by maternal supplementation and insecticide treated nets.
A few line-length refactors
Ran an interactive sim and verified that the stratifications appear as expected.

stratify wasting and stunting by birth-weight interventions

---

src/vivarium_ciff_sam/components/intervention.py
src/vivarium_ciff_sam/constants/scenarios.py
src/vivarium_ciff_sam/model_specifications/branches/scenarios.yaml

- *Category*: implementation
- *JIRA issue*: [MIC-2770](https://jira.ihme.washington.edu/browse/MIC-2770)
- *Research reference*: [Scenario documentation](https://vivarium-research.readthedocs.io/en/latest/concept_models/vivarium_ciff_sam/concept_model.html?highlight=ciff#simulation-scenarios)
Add the sam only scenario.
Verified that the new scenario scales up the correct interventions and the old ones still function as expected.

add sam only scale-up scenario

---

src/vivarium_ciff_sam/constants/data_values.py

Updating diarrhea prevalence and prev ratios
- *Category*: refactor
- *JIRA issue*: [MIC-2888](https://jira.ihme.washington.edu/browse/MIC-2888) 
- *Research reference*: this [PR](https://github.com/ihmeuw/vivarium_research/pull/793/files) and this [slack thread](https://ihme.slack.com/archives/C018BLX2JKT/p1646183763054739)
Updating diarrhea prevalence and prevalence ratios to force the diarrhea remission rate to == 1/4.3 days

Update vicious cycle data

---

src/vivarium_ciff_sam/data/loader.py

- *Category*: data artifact
- *JIRA issue*: [MIC-2931](https://jira.ihme.washington.edu/browse/MIC-2931)
Remove exposure under 6 months of zinc
Called get_data on these keys and verified results.

remove exposure of zinc supplementation under 6 months

---

src/vivarium_ciff_sam/components/wasting.py
src/vivarium_ciff_sam/constants/data_values.py
src/vivarium_ciff_sam/data/loader.py

- *Category*: research model change
- *JIRA issue*: [MIC-2930](https://jira.ihme.washington.edu/browse/MIC-2930)
Ran model

create vicious cycle diarrhea remission rate

---

src/vivarium_ciff_sam/data/loader.py

- *Category*: data artifact
- *JIRA issue*: N/A
There were bugs in the zinc artifact causing runs
Built artifact and ran simulation for several timesteps.

fix artifact building bug
